# Config package
# Re-export all constants from config.py for backward compatibility
from backend.config import (
    # Environment variables
    MONGO_URL, DB_NAME, JWT_SECRET, OPENAI_API_KEY,
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, FROM_EMAIL, FROM_NAME,
    FETCHAI_API_KEY, FLOKX_API_KEY,
    
    # Feature flags
    ENABLE_TRADING, ENABLE_LIVE_TRADING, ENABLE_AUTOPILOT,
    ENABLE_SELF_LEARNING, ENABLE_SELF_HEALING, ENABLE_CCXT,
    ENABLE_UAGENTS, PAYMENT_AGENT_ENABLED,
    
    # Exchange limits
    EXCHANGE_BOT_LIMITS, EXCHANGE_TRADE_LIMITS,
    
    # Global limits
    MAX_TRADES_PER_USER_PER_DAY, MIN_TRADE_PROFIT_THRESHOLD_ZAR,
    
    # Paper -> Live promotion criteria
    PAPER_TRAINING_DAYS, MIN_WIN_RATE, MIN_PROFIT_PERCENT, MIN_TRADES_FOR_PROMOTION,
    
    # Autopilot settings
    REINVEST_THRESHOLD_ZAR, NEW_BOT_CAPITAL, MAX_TOTAL_BOTS, TOP_PERFORMERS_COUNT,
    
    # AI Models
    AI_MODELS,
    
    # Risk settings
    STOP_LOSS_SAFE, STOP_LOSS_BALANCED, STOP_LOSS_AGGRESSIVE,
    
    # Rogue bot detection
    MAX_HOURLY_LOSS_PERCENT, MAX_DRAWDOWN_PERCENT
)

__all__ = [
    'MONGO_URL', 'DB_NAME', 'JWT_SECRET', 'OPENAI_API_KEY',
    'SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASSWORD', 'FROM_EMAIL', 'FROM_NAME',
    'FETCHAI_API_KEY', 'FLOKX_API_KEY',
    'ENABLE_TRADING', 'ENABLE_LIVE_TRADING', 'ENABLE_AUTOPILOT',
    'ENABLE_SELF_LEARNING', 'ENABLE_SELF_HEALING', 'ENABLE_CCXT',
    'ENABLE_UAGENTS', 'PAYMENT_AGENT_ENABLED',
    'EXCHANGE_BOT_LIMITS', 'EXCHANGE_TRADE_LIMITS',
    'MAX_TRADES_PER_USER_PER_DAY', 'MIN_TRADE_PROFIT_THRESHOLD_ZAR',
    'PAPER_TRAINING_DAYS', 'MIN_WIN_RATE', 'MIN_PROFIT_PERCENT', 'MIN_TRADES_FOR_PROMOTION',
    'REINVEST_THRESHOLD_ZAR', 'NEW_BOT_CAPITAL', 'MAX_TOTAL_BOTS', 'TOP_PERFORMERS_COUNT',
    'AI_MODELS',
    'STOP_LOSS_SAFE', 'STOP_LOSS_BALANCED', 'STOP_LOSS_AGGRESSIVE',
    'MAX_HOURLY_LOSS_PERCENT', 'MAX_DRAWDOWN_PERCENT'
]
